name: CI

on:
  pull_request:
    branches: [ main, staging ]
  push:
    branches: [ main, staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build, test, and analyze
        run: ./gradlew build jacocoTestReport pmdMain pmdTest checkstyleMain checkstyleTest --continue

      - name: Upload JaCoCo Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/jacocoHtml/

      - name: Upload PMD Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: build/reports/pmd/

      - name: Upload Checkstyle Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/